matrix:
- name: Markdown
  expect_match: false
  apsell:
    mode: en
  dictionary:
    wordlists:
    - .wordlist.txt
    output: wordlist.dic
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: false
      attributes:
      - alt
      ignores:
      - ':matches(code, pre)'
      - 'code'
      - 'pre'
      - 'blockquote'
  sources:
  - 'content/install-guides/**/*.md'
  - 'content/learning-paths/**/*.md'
  excludes:
  - 'content/learning-paths/automotive/intro/**/*.md'
  - 'content/learning-paths/automotive/tinkerblox_ultraedge/**/*.md'
  - 'content/learning-paths/cross-platform/gitlab-managed-runners/**/*.md'
  - 'content/learning-paths/cross-platform/llm-fine-tuning-for-web-applications/**/*.md'
  - 'content/learning-paths/cross-platform/psa-tfm/**/*.md'
  - 'content/learning-paths/embedded-and-microcontrollers/customer-support-chatbot-with-llama-and-executorch-on-arm-based-mobile-devices/**/*.md'
  - 'content/learning-paths/embedded-and-microcontrollers/edge_impulse_greengrass/**/*.md'
  - 'content/learning-paths/embedded-and-microcontrollers/linux-nxp-board/**/*.md'
  - 'content/learning-paths/laptops-and-desktops/win_profile_guided_optimisation/**/*.md'
  - 'content/learning-paths/laptops-and-desktops/win_python_onnx/**/*.md'
  - 'content/learning-paths/mobile-graphics-and-gaming/android_neon/**/*.md'
  - 'content/learning-paths/mobile-graphics-and-gaming/onnx/**/*.md'
  - 'content/learning-paths/servers-and-cloud-computing/fastpath/**/*.md'
  - 'content/learning-paths/servers-and-cloud-computing/gcc-lto/**/*.md'
  - 'content/learning-paths/servers-and-cloud-computing/jenkins/**/*.md'
  - 'content/learning-paths/servers-and-cloud-computing/vLLM-quant/**/*.md'
